base_discovery:
  container_name: syncthing-discovery
  image: itatabitovski/syncthing-server
  ports:
  - '8443:8443'
  restart: always
  entrypoint: /opt/syncthing/discosrv

base_relay:
  container_name: syncthing-relay
  image: itatabitovski/syncthing-server
  ports:
  - '22067:22067'
  restart: always
  entrypoint: /opt/syncthing/relaysrv
